name: Publish

on:
  push:
    branches:
      - main

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Build plugins
        shell: bash
        run: |
          ./scripts/build-all.sh
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"

      - name: List files
        shell: bash
        run: |
          ls -al target/wasm32-wasi/release

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump versions and publish
        shell: bash
        run: |
          ./scripts/bump-all.sh
        env:
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
