name: Publish

on:
  push:
    branches:
      - main

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check commit message
        id: check
        run: |
          commit_message=$(git log --format=%B -n 1)
          echo "Commit message: $commit_message"
          if [[ "$commit_message" == "Bump npm swc-plugin-fusion" ]]; then
            echo "Found match, setting skip to true"
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi
  build:
    name: Build
    needs: check_commit
    if: needs.check_commit.outputs.skip != 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Build plugins
        shell: bash
        run: |
          ./scripts/build-all.sh
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"

      - name: List files
        shell: bash
        run: |
          ls -al target/wasm32-wasi/release

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump versions
        shell: bash
        run: |
          ./scripts/bump-all.sh
        env:
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}

      - name: Publish npm packages
        run: |
          npm publish --workspaces --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
