name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0
  CI: "1"

jobs:
  test:
    strategy:
      fail-fast: false

    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-test"
          cache-on-failure: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt --check
        run: |
          cargo fmt --all -- --check

      - name: Run cargo test
        run: |
          cargo test --all --color always

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Build binary and run JS tests
        run: |
          npm test -w fusion-js-test
